version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/frontend.Dockerfile
    image: frontend:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules/
  redis:
    build:
      context: .
      dockerfile: docker/redis.Dockerfile
    image: "redis:latest"
    ports:
      - "6379"
    volumes:
      - "./redis/data:/data"
    restart: unless-stopped

volumes:
  node_modules:
